### PR TITLE
Manage fk-involved unique-constraints (refs #7)

### PR DESCRIPTION
**Pull request by sevdog**
Add an _helper-mixin_ and some utilities to better handle foreign-keys and `unique_together`.

Also some code cleanup.

### CODE REVIEW

**Comment by sevdog** [comment]
Need some more work to cover all use-case. Will update PR later.

**Comment by sect2k** [comment]
Thanks for this. If possible I would like to avoid using hidden form fields, but I currently don't have a clear idea how to achieve that, if at all possible. Let me go over the code and see if I can come up with something. If you have an idea how to achieve that, do share.

Keep in mind I would like to keep this Django 2.x compatible, so be careful not to use any code requiring later versions.

**Comment by sevdog** [comment]
Hidden field has some issue too: since _parents_ are put in exclusion array by  `get_exclude` default validation of form fails during _update_.

I am currently working on using `get_readonly_fields` instead of `get_exclude` (it should not alter UX too mutch on admin), but in this case it fails on _create_. I am digging into form/admin to find a good way to provide the right value.

Regarding compatibility I am pointing to Django 2.2 since its last supported branch of Django 2.x. I also want to avoid using any internal/hidden API to avoid this to break on core update. Its a good fact that there are no breaking-changes in admin/form in [Django 3.0](https://docs.djangoproject.com/en/3.0/releases/3.0/).

**Comment by sect2k** [comment]
I've gone over your PR, subadmin internals and also admin internals and your `SubAdminFormMixin` has me thinking this could maybe be achieved by using a custom `ModelForm` which would take care of setting the related fields on the instance. 

Will need to dig into forms internals a bit, to see where this could be best achieved, but if possible, I think this approach would have minimal side effects.

Don't let that stop you from exploring your approach, no guarantee mine would be better or work at all.

**Comment by sevdog** [comment]
I think to have found a solution. Basically is an hot-patch of form class which provides `related_instances` to specified form and updates `validate_unique` method in order to use it.

Tested with both normal edit and list-edit modes.

I belive that some unittest could improve assuring this works in different environment. But IMHO unittest should be added via an appropriate PR to the project in its entirety.

**Comment by sect2k** [comment]
Thank you for your contribution. I refactored the code a little, moved the code from `forms.py` into `__init__.py`, made some minor changes to `SubAdminFormMixin`, renamed `get_form` to `prep_subadmin_form` and made it a method on `SubAdmin`class, so it can be overriden by subclasses if needed.

Let me know if you encounter any issues, if not, I'll push a new release to pypi tomorrow.

If you're willing to contribute unit test, I will be more than happy to accept a PR and collaborate on any implementation details, but between raising twin babies, work and some other open source projects I'm currently working on, I find time to be a rare commodity.

**Comment by sevdog** [comment]
If I had some free time I will try to setup some unittests for this library.

Once unittest are set other changes would be easier (to test).

I would also like to try to reduce code duplication from standard admin, because this could simplify integration with future releases of django. But I know that this may be a very hard task since `SubAdminMixin` needs to redefine some method calls which do not seem easy to update without copying django code.

**Comment by sect2k** [comment]
Thanks, any contribution is welcome.

I tried to avoid code duplication, but like you noted, sometimes it's unfortunately impossible. 
In order to make that possible, modifications to django admin will gave to be made. Maybe one day when I have more time, I'll go over the code and prepare a PR for django and hope it gets accepted.

**Pull request merged**
