### PR TITLE
Added django 2.0 support

### PR DESCRIPTION
**Pull request by JostCrow**

### CODE REVIEW

**Comment by sect2k** [comment]
Hey @JostCrow, thanks for this, did't realize that was all it took for django 2.0 compatibility, but since django is dropping py2 support altogether, I will intend to do the same for subadmin and release a new version that is django2+ only.

If you have the time and desire to help with that, this PR can be a start. The general idea is to drop any py2 specifics and make sure code follows py3 idioms.

**Comment by henzk** [comment]
Hi,
this PR works really well for me. I use it in a couple of projects recently upgraded to django 2.
It would be great if this could be released on PyPI.
Are you still interested in that? I can remove py2 support as proposed.
Thank you!

**Comment by sect2k** [comment]
@henzk if you would be willing to remove py2 support, I will gladly merge this and release to pypi.
Thanks.

**Comment by henzk** [comment]
I'll get on that after christmas. Thanks @sect2k

**Comment by MerliX** [comment]
@henzk How is it going? Can I help you with this project? Thank you

**Comment by henzk** [comment]
hey, thanks @MerliX 

I did some work on transforming the code to py3 here: https://github.com/henzk/django-subadmin
Help is highly appreciated as i don't really have time to work on it currently.

**Comment by sect2k** [comment]
Hey @MerliX, any help making a proper version for py3 would be great. You can base it off work of @henzk or make a new PR. I you do this, I will make sure review, merge and release to Pypi ASAP.

Thanks BTW, any contribution is greatly appreciated.

**Comment by sect2k** [comment]
Latest 2.0.0. release is now Python 3 and Django 2.0+ compatible.

**Pull request closed without merging**
